\" dwn.1 manpage
\" .TH DWN 1 16\ May\ 2016 KLM Kurt\ Manion\'s\ Documentation
.Dd 16 May 2016
.Dt DWN 1
.Os UNIX
.Sh NAME
.Nm dwn
.Nd manipulate file most recently added to a folder
.Sh SYNOPSIS
.Nm
.Op Fl r
.Op Fl d Ar directory
.Op Fl n Ar num_files
.Nm
.Op Fl d Ar directory
.Op Fl o
.Op Fl f Ar flags
.Op Fl n Ar num_files
.Nm
.Op Fl d Ar directory
.Op Fl m Ar destination | Fl M
.Op Fl f Ar files
.Op Fl n Ar num_files
.Sh DESCRIPTION
Using
.Nm
without any flags prints the path of the file most recently added to the
.Pa ~/Downloads
directory to stdout.
The directory, from which the file is chosen, can be changed to any other valid traversable directory with the \fB\-d\fR option.
The number of files whose path should be written can be specified with the \fB\-n\fR option.
Scripts that use this mode of
.Nm
should force its usage with the \fB\-r\fR option to avoid unwanted effects caused by the end user aliasing the
.Nm
command.
This summarizes the first form shown in the Synopsis;
this can be used for inlining the filepath in another command,
and, thus, is the most versatile usage,
but a few convenience functions are also available.
.Pp
The second form opens the filepath normally outputed by
.Nm .
It is effectively the same as
.Sq open "`dwn -r`" ,
or, if on GNU Linux, 
.Sq xdg-open "`dwn -r`" .
.Pp
The third form employs the
.Xr mv 1
command,
essentially forming a synonym to `mv "`dwn -r`" \fIdestination\fR'.
.Nm
does not overwrite any file by default;
the
.Xr mv 1
command's \fB\-f\fR or \fB\-i\fR flag must be specified after
.Nm Ns ' Ns
s \fB\-f\fR option to force an overwrite.
.Sh OPTIONS
.Bl -hang
.It Fl d ,
This overrides the default directory
.Pa ~/Downloads
and will return the file most recently added to the supplied directory.
.It Fl r ,
The return option forces dwn to print the filepath to stdout.
This is designed be used in conjunction with a pipe.
If a alternative directory is to be specified one ought use the \fB-rd\fR construct
.Pq see examples section .
.It Fl n ,
Given a numeric argument, instead of operating on one file, operates on the specified number of files.  If there are less than that number of files in the directory
.Nm
simply operates on the present files.
.It Fl f ,
a list of options enclosed in quotes appearing after this option are passed to the command specified by any convenience forms.
.It Fl o ,
The open option opens the filepath using
.Xr open 1
or
.Xr xdg-open 1
depending on the operating system.
.It Fl m ,
The move option moves the file to the specified directory.
By default it does not overwrite files.
.It Fl M ,
An alias for
.Sq dwn -m .
Moves file to the current working directory.
By default it does not overwrite files.
.El
.Sh EXAMPLES
This opens the file most recently added to the desktop in textedit:
.Dl dwn -d ~/Desktop -f Qq -a /Applications/TextEdit.app
.Pp
or if you're currently in the home directory:
.Dl dwn -d Desktop -a TextEdit
.Pp
This will print the file's contents to the command-line:
.Dl dwn -d ~/Desktop -r | cat -
.Pp
Take advantage of \fB-rd\fR to change the flow of the command's invokation, 
.Dl dwn -rd ~/Desktop | cat -
.Pp
Move the most recently downloaded file to the Documents folder:
.Dl dwn -m ~/Documents
.Pp
Move the 5 most recently downloaded files to the Documents folder.
.Dl dwn -m ~/Documents -n5
.Sh AUTHOR 
dwn was created by
.An Kurt L. Manion
on 3 April 2016.
.Sh CONTACT
.Aq klmanion@gmail.com .
.Sh VERSION
version 3.0.2 \(em 8 September 2018.
