\" dwn.1 manpage
\" .TH DWN 1 16\ May\ 2016 KLM Kurt\ Manion\'s\ Documentation
.Dd 16 May 2016
.Dt DWN 1
.Os UNIX
.Sh NAME
.Nm dwn
.Nd manipulate file most recently added to a folder
.Sh SYNOPSIS
.Nm
.Op Fl r | Fl o | Fl m Ar destination | Fl M
.Nm
.Op Ar action
.Op Fl d Ar directory
.Op Fl n Ar num_files
.Op Fl f Ar flags
.Nm
.Op Ar action
.Op Fl S Ar skip_expr | Fl s Ar skip_num
.Nm
.Op Ar action
.Op Fl Evix
.Op Fl e Ar regex
.Sh DESCRIPTION
Using
.Nm
without any arguments prints to stdout the path of the file most recently added
to the specified directory, which, by default, is the
.Pa ~/Downloads
directory.
Inlining usage of
.Nm
in other commands allows the user to manipulate the file with the full power of
their unix distribution.
A few convenience forms have been added for commonly used file manipulation
commands,
and these actions are listed in the first synopsis line.
The following synopsis lines group options that control the way
.Nm
functions, and may be used with any of the actions enumerated in the first
synopsis line.
.Pp
The second synopsis line contains the options that control how the filepath is
obtained.
A directory other than the default may be specified with \fB\-d\fR.
Additional flags to be passed to the underlying command of the action form
before the filepath itself may be specified with \fB\-f\fR.
The number of files to obtain may be specified with \fB\-n\fR.
.Pp
The third synopsis line contains the options that allow one to skip over
certain files.
The \fB\-s\fR option, which is a convenience form for the more comprehensive
\fB\-S\fR option, takes a number and skips that many files that would have been
obtained.
This is useful for when one wishes to obtain a filepath or sequence of
filepaths that had been the most recent in a directory,
but since then have been pushed back by a few newer files.
The \fB\-S\fR option allows for more involved use cases.
.Pp
The fourth synopsis line contains the options that allow one to match 
filepaths with regular expressions.
Basic regular expressions are used unless the \fB\-E\fR flag is passed to
.Nm .
See
.Xr re_format 7
for additional information on the difference between the types of regular
expressions.
.Sh OPTIONS
.Bl -hang
.It Fl r ,
The return option forces the default behavior of
.Nm ,
printing the obtained filepath or filepaths to stdout.
This is designed be used in conjunction with piping or command substitution.
It is recommended to use this flag when scripting with
.Nm
if one desires to use its default behavior,
since the user may have aliased
.Nm
to use one of the other actions by default.
.It Fl o ,
The open option opens the obtained filepath or filepaths using
.Xr open 1
on Darwin and
.Xr xdg-open 1
on GNU Linux.
.It Fl m ,
The move option moves the obtained filepath or filepaths to the specified
directory.
By default it does not overwrite files.
.It Fl M ,
An alias for
.Sq dwn -m .
Moves the obtained filepath or filepaths to the current working directory.
By default it does not overwrite files.
.It Fl d ,
This overrides the default directory,
.Pa ~/Downloads ,
from which the selection is obtained.
.It Fl n ,
Given a numeric argument, instead of obtaining a filepath,
.Nm
obtains the specified number of files.
If there are less than that number of files in the directory
.Nm
obtains what is available.
.It Fl f ,
The string of options and flags following \fB\-f\fR are passed to the command
.Nm
will use on the obtained filepath or filepaths.
.It Fl S ,
The skip option takes an expression,
which is a comma separated list
whose element is either an address or a range of addresses.
These signify which files should be skipped when making the selection of
filepaths.
The address
.Sq 1
signifies the first file.
Only the first range may omit its lower bound;
this will skip the first n files, where n is the upper bound.
If the upper bound is ommited, or is
.Sq $ ,
the range has the significance of being the rest of the addresses starting at
the lower bound.
The skip expression may be prefixed with a
\(ga:',
a
.Sq ^ ,
or both in any order.
Prefixing the expression with a
\(ga:'
causes the list following it to be interpreted as a pattern
that repeats once the highest bound is reached.
This, then, has no effect if the highest bound is
.Sq $ .
Prefixing the expression with a
.Sq ^
negates the significance of the list following it,
such that it does not specify which files are to be skipped
but, rather, selected.
.It Fl s ,
Given a number, that number of files are skipped.
This is the same as
.Sq \-S "-n" ,
where n is the number passed to \fB\-s\fR.
.It Fl e ,
Only select files whose name matches the specified regular expression.
.It Fl E ,
Cause the regular expression passed to \fB\-e\fR to be interpreted as an
extended regular expression.
This is the same as passing
.Xr grep 1
its \fB\-E\fR flag to force
.Xr egrep 1
like behavior.
.It Fl v ,
Invert the behavior of \fB\-e\fR, so that files which match the regular
expression are excluded from the selection.
.It Fl i ,
Cause the regular expression passed to \fB\-e\fR to be matched
case insensitively.
.It Fl x ,
Cause the regular expression passed to \fB\-e\fR to only match
a file if it matches the whole name.
.El
.Sh EXAMPLES
This prints out the filepath most recently added to the desktop:
.Dl dwn -rd ~/Desktop
.Pp
This will print the file's contents to the command-line:
.Dl dwn -rd ~/Desktop | cat -
.Pp
Open the most recently downloaded file:
.Dl dwn -o
.Pp
Move the most recently downloaded file to the Documents folder:
.Dl dwn -m ~/Documents
.Pp
Move the five most recently downloaded files to the Documents folder.
.Dl dwn -m ~/Documents -n5
.Pp
Print out ten total filepaths, but skip a few that would otherwise have been
printed:
.Dl dwn -rn10 -S Ns Qq 2-5,8
.Pp
Print out the third and fifth filepath:
.Dl dwn -rS Ns Qq ^3,5
.Pp
Print out every other file in the directory in order of their creation:
.Dl dwn -rS Ns Qq :2
.Pp
Print out the five most recently created text files
.Dl dwn -rn5 -e'\.txt'
.Sh AUTHOR 
dwn was created by
.An Kurt L. Manion
on 3 April 2016.
.Sh CONTACT
.Aq klmanion@gmail.com .
.Sh VERSION
version 3.3.0 \(em 15 September 2018.
